### ISSUE TITLE
Detect composer installation failure

### ISSUE THREAD

**Issue by atymic** [Harmonic/laravel-preset#4]
Using this on another project :D
Using my PR for l6, #2 but I think this applies anyway.

If composer install fails, the installer continues, but the app is left in a broken state. 

We should instead catch the failure exit code, and present the error to fix to the user.

Happy to PR :)

**Comment by craigharman** [comment]
Agreed, would love to see a PR for this @atymic 
Thanks.

**Comment by atymic** [comment]
I've created a PR with that and a bunch of other improvements :)
